vich_uploader:
    db_driver: orm

    mappings:
       featured_profils:
            uri_prefix: '%app.path.featured_profils%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.featured_profils%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true